apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: juphc-tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: build-image
    - name: repo-url
    - name: branch
      default: main
  tasks:
  
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
        
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init

    - name: npminstall
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: npminstall
        kind: Task
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: jasmine
        kind: Task
      runAfter:
        - npminstall

    - name: build
      workspaces:
        - name: output
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: $(params.build-image)
      runAfter:
        - tests
